### PR TITLE
Assert Is Indeterminate for Compose Ultron

### PR DESCRIPTION
**Pull request by Darocs**
Added `assertIsIndeterminate`, now the project architecture should not conflict with what I added

The test is still passing

### CODE REVIEW

**Review by alex-tiurin — APPROVED** [review]
Nice job!

**Comment by alex-tiurin** [comment]
You can "Squash and merge" this PR

**Comment by Darocs** [comment]
Sorry, but I can't merge this PR because if I understand correctly, where it should say merge pull request, it says the following: 
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Comment by alex-tiurin** [comment]
Alright, I see ) welcome to the contributors!

**Comment by Darocs** [comment]
Thanks!

**Pull request merged**
